### ISSUE TITLE
Feature Request: Portal standalone with vscode goto definition

### ISSUE THREAD

**Issue by Cyrik** [djblue/portal#101]
Currently launching portal with (p/open {:launcher :vs-code}) does nothing if there is no portal plugin, but if you call "go to definition" in the standalone launcher it tries to do that in emacs.
It would be great to have the launcher option separate from the IDE selection option.

If you want to I can write a PR for this once I find some time.

**Comment by djblue** [comment]
I really like the idea, let me know if https://github.com/djblue/portal/commit/65baf7c9a34218b3ad3332903385148b532e258d works for you.

**Comment by Cyrik** [comment]
Thanks for quick response. I didn't have the time to try it yet, but the code looks good!
