### ISSUE TITLE
Windows VS Code extension fails to display

### ISSUE THREAD

**Issue by kjothen** [djblue/portal#107]
The VS Code integration does not seem to fire-up on Windows. It appears to be a problem with making the directory `~/.portal`, probably an issue with an errant leading `/`.

```This extension has reported 1 uncaught error

Uncaught Errors (1)
ENOENT: no such file or directory, mkdir '/C:/Users/ABC123/.portal'
```

**Comment by djblue** [comment]
Interesting, thanks for the bug report @kjothen! I will look into this if I get some time. The relevant code can be found [here](https://github.com/djblue/portal/blob/master/src/portal/extensions/vs_code.cljs#L81-L94) if you are feeling adventurous.

**Comment by djblue** [comment]
@kjothen I think #108 should fix this 💯
