### ISSUE TITLE
Bug dev: dev-cljs aliases not defined

### ISSUE THREAD

**Issue by davidpham87** [djblue/portal#116]
Hello,

I am trying to add a new viewer to portal (adding plotly charts), and as I am using emacs, it occurred to me that dev-cljs was not defined in deps.edn.

Best regards,
David

**Comment by djblue** [comment]
Sorry about that, let me know if https://github.com/djblue/portal/commit/f36d60316a08246b6f0ac59cf70cf19262426cba fixes it 👌
