### ISSUE TITLE
Should it work on windows?

### ISSUE THREAD

**Issue by MrGung** [djblue/portal#12]
I am using Windows 10, starting portal in the REPL with

`clojure -Sdeps '{:deps {djblue/portal {:mvn/version """"""0.4.0""""""}}}'`

I then follow the example from the webpage:

```
Clojure 1.10.1
user=> (require '[portal.api :as p])
nil
user=> (p/open)
nil
user=> (p/tap)
nil
user=> (tap> :hello)
```

A browser-tab is opened (on p/open) but nothing is ever displayed. The window stays blank...

**Comment by djblue** [comment]
It should. Can you try version `0.3.1` and see if that works?

**Comment by MrGung** [comment]
It works fine with `0.3.1`!

**Comment by djblue** [comment]
I had to add a custom [http server](https://github.com/djblue/portal/blob/master/src/portal/http_socket_server.clj) to support [babashka](https://github.com/borkdude/babashka). I only tested it on osx and linux. Guess it doesn't work on windows.

What browser does it open in? Also, can you get any information about network activity in the browser debug tools?

**Comment by djblue** [comment]
Should be fixed by https://github.com/djblue/portal/commit/e13a9d99c680a4be0e5aab4e6bb31e1761a2f0c4 and released in [`0.4.1`](https://github.com/djblue/portal/releases/tag/0.4.1).

**Comment by MrGung** [comment]
It opens in my default browser, which is Opera. I also copied the URL to Chrome. Same result: the only network-traffic is a GET for the favicon (which results in a 404).

**Comment by djblue** [comment]
Does 0.4.1 work for you?

**Comment by MrGung** [comment]
It does. Thanks!

**Comment by djblue** [comment]
Sweet, thanks for the bug report!
