### ISSUE TITLE
VSCode Extension: allow for dragging the tab around

### ISSUE THREAD

**Issue by orestis** [djblue/portal#125]
I'm not sure if this is a VSCode bug, but I realised that when I'm trying to drag the Portal tab around, the whole window is also being dragged with it. A very strange behaviour, as if the drag events are passed to both the tab, and the window itself.

To reproduce:

* Make a left/right split in VSCode, open a few files in each side.
* Open portal via the `extension.openPortal` command (it shows up always on the left side)
* Try to drag *any* editor tab from the left side.

Expected behaviour:

* The editor tabs can be rearranged

Actual behaviour:

* The whole window is moved 

The behaviour persists even if the Portal tab is closed, until a window reload.
The right side split is unaffected.

**Comment by djblue** [comment]
Hi @orestis, thanks for opening up this issue 👍  Quick question, what operating system is this on? I can't seem to reproduce on OSX.

**Comment by djblue** [comment]
I did notice the issue on windows and https://github.com/djblue/portal/commit/e625065fda64b3e85fe3ba212a5b061bd613f340 seems to fix it 👌

**Comment by djblue** [comment]
This should be resolved with [`0.26.0`](https://github.com/djblue/portal/releases/tag/0.26.0)
