### ISSUE TITLE
Possibility to navigate through data from Datomic database

### ISSUE THREAD

**Issue by velios** [djblue/portal#126]
Structures with datomic.query.EntityMap

**Comment by djblue** [comment]
Hi @velios, can you elaborate on your issue? Currently any value that implements the [`nav`](https://clojuredocs.org/clojure.core.protocols/nav) protocol should be usable via Portal.

**Comment by velios** [comment]
Thx for your interest. In my project i use Datomic, which i found convinient with Clojure.
In my repl i can do this
(def e (d/entity <db> <entity-id>)) 
and e will be instance of (instance? datomic.query.EntityMap asset-def) -> true
which is navigable (satisfies? clojure.core.protocols/Navigable asset-def) -> true
From REPL i can navigate from entity any level to depth (-> e :e-ns/link-to-another-e-1 -> :another-e-1/link-somewhere-else -> ...)
I was hoping that through the portal I would be able to visually navigate through my entity in the same way as I do it in the console.

I add some explanatory video, because maybe i just not set right options in portal

https://user-images.githubusercontent.com/9293462/167995668-3333f66c-f37f-4f93-9013-6edeb728b4c0.mp4

**Comment by djblue** [comment]
It looks to me like what you are leveraging at the repl is that `datomic.query.EntityMap` implements `clojure.lang.ILookup`. What does calling [`datafy`](https://clojuredocs.org/clojure.datafy/datafy) on it do?

**Comment by velios** [comment]
I tried same in REBL tool and it works like portal. Probably it isn't possible without radically changes. I hope sometime drill down datomic data in Portal will work like in Datomic Console. I add explanatory videos if you don't see Datomic Console before. Thx for you answers.

https://user-images.githubusercontent.com/9293462/168412223-2dcf9d06-dc42-4dd0-8c47-4cca4c2c42c7.mp4

.

**Comment by velios** [comment]
Hello. One more question if it possible.

I add navigation through datomic data in my project and it works like charm
` (extend-protocol clojure.core.protocols/Datafiable
   datomic.query.EntityMap
   (datafy [o] (into {} o)))

 (extend-protocol clojure.core.protocols/Navigable
   Object
   (nav [coll k v]
     (clojure.datafy/datafy v)))`

Quick demo how it works

https://user-images.githubusercontent.com/9293462/188439336-fae4e66c-29b8-4d77-a539-a8b95fe4b063.mp4

How i can change representation of data. In my case {:db/id ...} to something like "<db/id>/<code>"
Which mechanism use portal to draw it.

I tried
- extend portal.runtime.cson with my datomic.query.EntityMap type
- extend print-method for datomic.query.EntityMap, it partically works, change representation, but lost ability to navigate
- reimplemnt identity for datomic.query.EntityMap object

**Comment by djblue** [comment]
Not sure I understand the question. Do you want to customize how entity maps are rendered or do you want them to be rendered as a string?

**Comment by velios** [comment]
> Not sure I understand the question. Do you want to customize how entity maps are rendered or do you want them to be rendered as a string?

Want to understand how portal choose short-form of value and how return short-form which i like for specific class. In my case i want to render string and if i click RET on it fall into long-form of value(clojure.datafy/datafy)

**Comment by djblue** [comment]
I think something like:

```clojure
(defn ->ids [entity-maps]
  (with-meta
    (mapv #(str "db/id / " (:db/id %)) entity-maps)
    {`clojure.core.protocols/nav
     (fn [_coll k _v]
       (into {} (nth entity-maps k)))}))
```

Might be what you are looking for.

**Comment by djblue** [comment]
Also, you could do:

```clojure
(with-meta
  [{:db/id 0} {:db/id 1}]
  {:portal.viewer/default :portal.viewer/tree})
```
If the main issue is that the vector is collapsed by default.

**Comment by velios** [comment]
I did what i want by redifene print-method, but strange. If i return string from print method then portal render it as symbol. But symbols not able to use spaces. 

```
(defmethod clojure.core/print-method datomic.query.EntityMap [x writer]
  (print-simple (str x) writer))
```

It also works same way with any redefined class

**Comment by djblue** [comment]
I think you might need to include the "" around the value if you want it to render as a string.

**Comment by velios** [comment]
It works! Last piece to puzzle i tried to solve this week. Just as amazing a response as the product you're working on. Thank you a lot.
