### ISSUE TITLE
Allow sorted-map to be displayed on it's original order

### ISSUE THREAD

**Issue by bortexz** [djblue/portal#128]
Portal tries to sort any map on it's keys, even sorted-maps that might have a different ordering (using custom comparator). Ideally, sorted-maps would be printed on their original order instead of trying to sort them.

**Comment by djblue** [comment]
Thanks for opening the issue! https://github.com/djblue/portal/commit/b0b962ad0f6964be96414b7e07092ed3869661f8 should address this issue and be part of the next release.
