### ISSUE TITLE
When using IntelliJ extension, enable jump-to-code in `:portal.viewer/stack-trace` view

### ISSUE THREAD

**Issue by coyotesqrl** [djblue/portal#131]
(I'm sure this could be implemented for VSCode as well; that would be a separate ticket, I think.)

When working on...let's call it linguine code so as not to be _too_ crude...I find I often write taps like the following:
```clojure
(tap> {:data1 d1 :data2 d2 :whence (ex-info "whence" {})})
```
so I can walk back through the callstack. It's all there, and I can manually move around in the editor to the ns and line I need, but it would be nice if it the integrated Portal window could automatically jump when I click on a line in the stack trace view.

I know that it would likely use the `com.intellij.util.PsiNavigateUtil.navigate` method, but I don't know how to attach that UI action in the plugin.

**Comment by djblue** [comment]
https://github.com/djblue/portal/commit/8a299f48e25ab888c1cf2208b409f82cd4ea1d55 should be a generic approach to solving this issue, although editor specific improvements can still be made.

**Comment by djblue** [comment]
Should now be available as part of [0.45.0](https://github.com/djblue/portal/releases/tag/0.45.0).
