### ISSUE TITLE
Feature request: navigate multiple level at the same time

### ISSUE THREAD

**Issue by schneiderlin** [djblue/portal#136]
thanks for the great tool!

screenshot from hacker news demo
<img width="579" alt="image" src="https://user-images.githubusercontent.com/17421608/187057571-ead582e5-abf6-4832-8cda-3f38c0e8bcfd.png">
currently, if I click on the item id. it would just return the id as a value.

I want the user to be able to supply a nav function in meta similar to this
```
(defn nav-multiple [_coll k v]
    (if (= k [:submitted :nth])
      (let [item-id v]
        (nav-item item-id))
      v))
```
when the id is clicked, invoke `nav-item`. achieve the same effect as clicking on the `submitted` vector, then click on the id.

might be related to #77

**Comment by djblue** [comment]
@schneiderlin Good catch, I think attaching metadata directly to the sub collections should do the trick 👌
