### ISSUE TITLE
Shortcut for `datafy`

### ISSUE THREAD

**Issue by pfeodrippe** [djblue/portal#139]
Hi,

Would it be possible to create a shortcut for `datafy` (e.g. `SHIFT + ENTER`)? Maybe it was discussed before, but I didn't find anywhere.

Thanks

**Comment by djblue** [comment]
@pfeodrippe that sounds like a good idea to me, mind putting up a PR? It should fit nicely under [here](https://github.com/djblue/portal/blob/master/src/portal/ui/commands.cljs#L271).

**Comment by pfeodrippe** [comment]
Done, thanks @djblue o/ 

I have tested using by using `bb dev` and then running `user.clj`, it was a sweet piece of cake! Great work here
