### ISSUE TITLE
Ability to start Portal without UI

### ISSUE THREAD

**Issue by pfeodrippe** [djblue/portal#145]
Am I able to start Portal without a UI? 

For example, a `p/open` that does not open a window, it just starts the server (so I can link later somewhere using the new `p/url` function), returning the usual Portal object (`p/start` returns a map).

**Comment by djblue** [comment]
@pfeodrippe, I recently added https://github.com/djblue/portal/commit/0dfe3425cc10671285c709decde97173cb863059 to allow users to disable the launcher with `{:launcher false}`. It will be part of the next release.

**Comment by pfeodrippe** [comment]
> @pfeodrippe, I recently added [0dfe342](https://github.com/djblue/portal/commit/0dfe3425cc10671285c709decde97173cb863059) to allow users to disable the launcher with `{:launcher false}`. It will be part of the next release.

Oh nice!! This is why your gist in Clojurians for Portal in Clerk wasn’t working ahahahahahaha sorry,  man. 

Keep the good work, don’t forget to take some good breaks
