### ISSUE TITLE
Docs for cider mention a .dir-locals.el that doesn't exist

### ISSUE THREAD

**Issue by Ramblurr** [djblue/portal#152]
https://github.com/djblue/portal/blob/3313b7baea86c422b06c3458d0362aa54272b745/doc/dev/editors.md?plain=1#L28

This linked file doesn't seem to exist in the repo anymore.

**Comment by djblue** [comment]
Good catch @Ramblurr, this use to live in the README so it should actually point to the one in the root of the repo. Did you want to put up a PR with the fix?
