### ISSUE TITLE
Unable to load VSCode Extension

### ISSUE THREAD

**Issue by rlhk** [djblue/portal#156]
I'm on the latest macOS Ventura 13.0.1 &. VSCode 1.73.1

Tried install, disable & enable the extension but always got the following error. Any clue?

<img width="660" alt="Screenshot 2022-12-01 at 16 07 38" src="https://user-images.githubusercontent.com/17818753/204999608-5619305f-8dc0-4a7f-b7b1-ce37d502ed4b.png">

**Comment by djblue** [comment]
@rlhk  I have the same version of vscode, but a previous version of OSX and can't seem to reproduce. Can you share any additional info about your setup? Also, does reinstalling the extensions help?

**Comment by rlhk** [comment]
Just found out it's VSCode multiple instance issue: https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai

**Comment by djblue** [comment]
Thanks for info!
