### ISSUE TITLE
vs-code extension not working in "remote" connection

### ISSUE THREAD

**Issue by behrica** [djblue/portal#157]
I use Calva in a "remote-connection".
The portal-vs-code-extension windows opens for me, after rnning:

```clojure
(def p (p/open {:launcher :vs-code})) 
```

but is completely empty, and does not render anything
No error message seen.

Is it supposed to work ?

**Comment by behrica** [comment]
some background and workarround here:

https://app.slack.com/client/T03RZGPFR/CBE668G4R/thread/CBE668G4R-1670066051.016199

**Comment by behrica** [comment]
By "remote connection" I talk about a complete external machine connected to via "Remote-SSH: Connect to Host..." first and then open my clojure files remotely, which starts Calva and the code-portal extension.

**Comment by djblue** [comment]
@behrica The difficult bit here is that the clojure repl process (remote) needs to be able to make an http request to the vs-code process (local). When the processes are on different machines, it makes this coordination more challenging. So I would describe this setup as currently unsupported without re-doing how the repl host and vs-code extension communicate.

**Comment by behrica** [comment]
ok, accepted answer.

Maybe the work around can be documented somewhere.

On the other side for me one of the biggest selling points of "vs-code" is the "transparent remote".
But I can understand that any extension need to make probably an extra effort to be "fully remote compliant".
I would think that there is some support for this in vs-code APIs, but I know nothing about it., just guessing

**Comment by behrica** [comment]
I confirm, its fixed
