### ISSUE TITLE
Question regarding js dependency for custom viewer

### ISSUE THREAD

**Issue by maacl** [djblue/portal#164]
What would be the best way to make a js dependency (in this case https://timeline.knightlab.com/) available to use in a custom viewer? I have it available in my project, but unsure how to load it into the portal UI.

**Comment by djblue** [comment]
Hi @maacl, currently there isn't an easy way to bring in js dependencies outside of manually injecting a script tag.

**Comment by maacl** [comment]
OK. Where should I place the files, if I want cross scripting issues?

**Comment by djblue** [comment]
@maacl I think https://github.com/djblue/portal/commit/70ce1a2622ac4b25a029b7bb14f0053d76070064 might end up solving your problem in the next release. It will allow cljs code loaded via sci to pull js from node_modules.

**Comment by djblue** [comment]
This issue should be resolved as of [0.37.0](https://github.com/djblue/portal/releases/tag/0.37.0). Please let me know if you run into any issues.

**Comment by maacl** [comment]
Thanks, I will give it a try.
