### ISSUE TITLE
The UI seems to lock up if you tap an infinite lazy seq

### ISSUE THREAD

**Issue by l0st3d** [djblue/portal#17]
I've not looked into it, but I assume it's trying to display the whole thing. It might be worth detecting this and implementing some pagination or something??

**Comment by l0st3d** [comment]
This is on an JVM, using CIDER.
    ;; CIDER 0.27.0snapshot (package: 20200813.2112), nREPL 0.8.0
    ;; Clojure 1.10.1, Java 14.0.1

**Comment by l0st3d** [comment]
Doing something like this
```
  (require '[portal.api :as portal])
  (portal/open)
  (portal/tap)
  (tap> (range))
```
takes longer than my patience to return, and seems to stop me from running `cider-quit`.

**Comment by djblue** [comment]
Hi @l0st3d, this happens on the host side of things when the data is being [serialized as transit](https://github.com/djblue/portal/blob/master/src/portal/runtime/transit.clj#L25) before it's shipped up to the UI. I think if you `(tap> (range))` in REBL, they truncate to 10k items, which would be a reasonable solution for portal as well. I tend not to run into this problem, so it isn't a priority for me right now, but if you'd like to submit a PR, I would be happy to review!

**Comment by djblue** [comment]
@l0st3d I changed my mind and went ahead and implemented a solution in #18

**Comment by l0st3d** [comment]
That seems like a reasonable solution too. Will have a test. Many thanks.

Just out of interest, how much effort do you think implementing pagination would be?

**Comment by djblue** [comment]
@l0st3d I just updated #18 to lazily fetch seqs. It does so in batches of 100. As you scroll, more data from the seq is fetched.
