### ISSUE TITLE
portal display for Dates is incorrect 

### ISSUE THREAD

**Issue by CharlotteNewcomer** [djblue/portal#181]
When tapping date objects portal displays the date incorrectly.  Here are some examples: 
```clojure
#inst "0001" ;; => #inst "0001-01-01T00:00:00.000-00:00"
(tap> #inst "0001") ;; [portal displays]: #inst "0000-12-30T00:00:00.000Z"

#inst "1000" ;; => #inst "1000-01-01T00:00:00.000-00:00"
(tap> #inst "1000") ;; [portal displays]: #inst "1000-01-06T00:00:00.000Z"
```

**Comment by coyotesqrl** [comment]
That's actually a known (but not documented) difference between Clojure and Clojurescript date interpretation.
https://github.com/clojure/clojurescript-site/issues/367

**Comment by djblue** [comment]
I think for now I'll add this to the Portal documentation as a [limitations](https://github.com/djblue/portal/blob/master/doc/limitations.md).
