### ISSUE TITLE
Custom icon for Portal window

### ISSUE THREAD

**Issue by brdloush** [djblue/portal#20]
Hello,

it would be nice if the browser window, that gets spawned by Portal, had its own custom portal icon.

Currently Portal window receives generic browser icon (green Google Chrome icon in my case) and therefore it is quite hard to find it when switching between windows using alt-tab. Similarly, it's confusing to see portal windows being grouped with other browser windows in Plank dock (on linux) or similar dock.

Not sure if it's achievable by some chrome CLI options, or via some system-specific tools such as `xseticon`, `xprops` etc.

Just an idea to consider.

BTW portal is a great tool, you're doing really awesome work! :clap: :+1:

**Comment by brdloush** [comment]
btw on linux I had some success with the [approach mentioned here](https://community.foundry.com/discuss/post/1046531), but only with some windows. This approach didn't work for chrome windows unfortunately. Not sure why it sometimes work and sometimes not.

**Comment by djblue** [comment]
Hi @brdloush,

This is an interesting problem. I'll see if there is anything that can be passed to chrome to set the system icon.

Thanks for the kind words!

**Comment by brdloush** [comment]
I managed to succesfully change the task-switcher icon of already-running portal window using `xdotool search -name "portal - jvm - 0.6.1"  set_window --classname "firefox"`. 

Unfortunately I have no idea how the actual icon gets derived from this classname (which is effectively `WM_CLASS`), nor do I know how to register your own icon using this approach.

**Comment by djblue** [comment]
@brdloush  I've been working on https://github.com/djblue/portal/tree/pwa that I think might accomplish this. The idea is that you could install a [progressive web app](https://web.dev/progressive-web-apps/) from github that acts as a host for your local instance of portal. The pwa can have a theme color and an icon :100: The hardest part has been getting the app-id after install but I got it mostly working for osx and linux.

**Comment by djblue** [comment]
I'm closing this as it is mostly solved by using portal as a pwa. The launcher will [check to see if you have it installed](https://github.com/djblue/portal/blob/master/src/portal/runtime/jvm/launcher.clj#L35-L54) and prefer that over the normal `--app` chrome-flag. @brdloush feel free to open a new issue if you run into any problems.
