### ISSUE TITLE
Bug with test reporting and Portal middleware

### ISSUE THREAD

**Issue by seancorfield** [djblue/portal#208]
Definitely an edge case: in HoneySQL, there's a test that uses an unhashable `Object` to test a specific equality check and it "breaks" Portal.

Repro case here: https://github.com/seancorfield/portal-bug-repro

I tracked it as far as the `clojure.test` interceptions that Portal's middleware puts in place. Hope the repro case is helpful!

**Comment by djblue** [comment]
Thanks for the repro case! I think https://github.com/djblue/portal/commit/486bcc59ed8dff56a4deec3a3d27bf93c1f5ba92 should resolve the issue.

**Comment by seancorfield** [comment]
Nice! Thank you.
