### ISSUE TITLE
BufferedImage

### ISSUE THREAD

**Issue by genmeblog** [djblue/portal#213]
Is there a way to display JVM BufferedImage object?

**Comment by djblue** [comment]
@genmeblog, currently not directly. An easy work around would be to turn that object into a byte array then Portal should be able to render the image.

**Comment by genmeblog** [comment]
What should be a structure of such byte array? Encoded png or jpg?

**Comment by djblue** [comment]
I think either should work since I just pass the info directly to the web browser, but I've only tested png byte arrays.

**Comment by genmeblog** [comment]
Ok, thanks!
Do you plan to add BufferedImage in the near future?

**Comment by djblue** [comment]
Going to close this for now, feel free to open it back up if you have more questions.
