### ISSUE TITLE
IntelliJ Portal tab icon barely visible with "Light" theme

### ISSUE THREAD

**Issue by devurandom** [djblue/portal#225]
My IntelliJ UI theme (Settings -> Appearance & Behaviour -> Appearance -> Theme) is "Light". The Portal tab icon is barely visible:
 ![image](https://github.com/djblue/portal/assets/63082/5e386846-0cf7-4240-97a7-b2b45202bcd5)
It took me several minutes and the screenshot in https://github.com/djblue/portal/issues/138#issuecomment-1245956611 to find it.

**Comment by djblue** [comment]
@devurandom that's unfortunate, https://github.com/djblue/portal/commit/35342728463f2d0589000d54ef95a494d5f35ea3 should fix that and work for both dark and light themes 👌
