### ISSUE TITLE
IntelliJ plugin clips :portal.viewer/inspector selection box

### ISSUE THREAD

**Issue by devurandom** [djblue/portal#229]
The selection box at the bottom of the Portal IntelliJ tab is clipped / cut off: 
![image](https://github.com/djblue/portal/assets/63082/31f1042f-d5cc-4402-9990-b246190be4a9)

**Comment by djblue** [comment]
As of https://github.com/djblue/portal/commit/cd1cf936e908ba120de0186b44220234ac1e91e4, which was release in [`0.58.0`](https://github.com/djblue/portal/releases/tag/0.58.0), this should no longer be an issue as the a html select is no longer used.
