### ISSUE TITLE
VegaLite data values using TableCloth rows as maps

### ISSUE THREAD

**Issue by timothypratley** [djblue/portal#232]
[TableCloth](https://scicloj.github.io/tablecloth/) is a popular way to work with datasets. Visualizing with VegaLite via Portal is very convenient.

Sadly, the most natural way to assign the data of the visualization:

    (tc/rows flip-frequency-distribution :as-maps)

Produces exactly the right thing, but because the maps are actually `tech.v3.datatype.FastStruct`, Portal serialization produces the wrong output:

```
"values": {
      "object": {
        "meta": null,
        "Y": 6,
        "O": [
          {
            "Kb": null,
            "name": "tag",
            "la": "tag",
            "_hash": null,
            "P": 2153775105,
            "aa": 4096
          },
```

These "objects" should be serialized as "maps".

```
(first (tc/rows flip-frequency-distribution :as-maps))
=> {:score 6, :count 1}
(map? (first (tc/rows flip-frequency-distribution :as-maps)))
=> true
(type (first (tc/rows flip-frequency-distribution :as-maps)))
=> tech.v3.datatype.FastStruct
```

There are several workarounds including using a CSV string instead or manually making (non-record) plain maps. But it seems like maybe an easy thing to fix in the way the json is serialized.

**Comment by djblue** [comment]
Hi @timothypratley, thanks for reporting this issue.

I feel like https://github.com/djblue/portal/commit/dc33869fef516195290c2cc35e901bbf07208fb0 should fix this issue. Did you want to give it a try locally?

**Comment by djblue** [comment]
Thanks for verifying this, I should get a release out within the next week.
