### ISSUE TITLE
`portal.repl/wrap-repl` / `portal.api/repl` seem to be broken

### ISSUE THREAD

**Issue by Ramblurr** [djblue/portal#248]
I wanted to try my hand at creating a custom viewer, following along with [the Custom Viewer docs](https://cljdoc.org/d/djblue/portal/0.58.2/doc/guides/custom-viewer) I encountered this error: 

```
"Please start nREPL with `portal.nrepl/wrap-repl` middleware to enable the portal subrepl"
```

Here is a minimal repro:

```clj
;; src/user/clj
(ns user)

(comment
  (do
    (require '[portal.api :as p])
    (def p (p/open {:theme :portal.colors/gruvbox}))
    (add-tap #'p/submit))

  (p/repl p)
  ;;;
  )
```

```clojure
;; deps.edn
{:paths   ["src"]
 :deps    {org.clojure/clojure {:mvn/version "1.12.0"}}
 :aliases {:dev {:extra-deps {djblue/portal     {:mvn/version "0.58.2"}
                              nrepl/nrepl       {:mvn/version "1.3.0"}
                              cider/cider-nrepl {:mvn/version "0.50.2"}}
                 :main-opts  ["-m" "nrepl.cmdline"
                              "--middleware" "[cider.nrepl/cider-middleware,portal.nrepl/wrap-portal]"]}}}

```

Running with `clj -M:dev`, and then connecting with cider and evaluating the forms gives me:

![image](https://github.com/user-attachments/assets/88affc9c-d395-428a-a328-cbfaeafbc571)

**Comment by djblue** [comment]
@Ramblurr I think you only have the `portal.nrepl/wrap-portal` middleware enabled, but `portal.nrepl/wrap-repl` is required for the repl. If you want to add all portal middleware, you can use [`portal.nrepl/middleware`](https://github.com/djblue/portal/blob/master/src/portal/nrepl.clj#L295-L299)

**Comment by Ramblurr** [comment]
Oh gosh, many thanks :pray: My brain stopped parsing at `portal.nrepl/wrap-` because it assumed there was just one
