### ISSUE TITLE
Dies on objects

### ISSUE THREAD

**Issue by eneroth** [djblue/portal#25]
Portal dies on objects, it seems.

For example, after tapping something like,

```Clojure 
{:name "sara" :email "sara@sara.com" :fn println}
```

the session is busted, and it seems to receive no further values until the JVM is rebooted.

**Comment by djblue** [comment]
![Screen Shot 2020-12-04 at 8 37 45 AM](https://user-images.githubusercontent.com/1986211/101182918-ffdac680-360b-11eb-8e35-d0826ee546c2.png)

Hi @eneroth, thanks for the issue. This is what I get locally. It looks like you have a trailing `]}`, is there more data?

**Comment by eneroth** [comment]
Sorry, that was an oops when I copied and pasted the code.

It seems that the issue occurs when I run it from a project folder, where I must have a dep that overrides or conflicts with something in Portal. 

After some poking around, it seems that if I remove [Fulcro](https://github.com/fulcrologic/fulcro) as a dependency, it works fine. So it would seem that this comes down to dependency conflicts between Fulcro and Portal:

```
com.fulcrologic/fulcro 3.4.6
  cljsjs/react-dom 16.13.0-0
  com.cognitect/transit-cljs 0.8.264
    com.cognitect/transit-js 0.8.861
  org.clojure/clojurescript 1.10.773
    org.clojure/google-closure-library 0.0-20191016-6ae1f72f
      org.clojure/google-closure-library-third-party 0.0-20191016-6ae1f72f
    com.google.javascript/closure-compiler-unshaded v20200315
      com.google.elemental2/elemental2-core 1.0.0-RC1
      com.google.errorprone/error_prone_annotations 2.3.1
      com.google.jsinterop/jsinterop-annotations 1.0.2
      com.google.javascript/closure-compiler-externs v20200315
      com.google.guava/guava 25.1-jre
        org.codehaus.mojo/animal-sniffer-annotations 1.14
        com.google.j2objc/j2objc-annotations 1.1
        org.checkerframework/checker-qual 2.0.0
        com.google.code.findbugs/jsr305 3.0.2
      args4j/args4j 2.0.26
      com.google.jsinterop/base 1.0.0
      com.google.re2j/re2j 1.3
      com.google.protobuf/protobuf-java 3.11.1
      com.google.code.gson/gson 2.7
  cljsjs/react 16.13.0-0
  com.taoensso/sente 1.16.0-alpha1
  com.cognitect/transit-clj 1.0.324
    com.cognitect/transit-java 1.0.343
      org.msgpack/msgpack 0.6.12
        com.googlecode.json-simple/json-simple 1.1.1
        org.javassist/javassist 3.18.1-GA
      javax.xml.bind/jaxb-api 2.3.0
  cljsjs/react-dom-server 16.13.0-0
```

Could this be the reason for the issue I'm encountering?

**Comment by djblue** [comment]
I think you are correct. You are running into this issue:

https://github.com/djblue/portal/blob/master/deps.edn#L13

**Comment by eneroth** [comment]
That's it, chucking the override in there seems to make everyone happy.

```Clojure 
  {:extra-deps {djblue/portal {:mvn/version "0.6.4"}}
   :override-deps {org.clojure/clojurescript
                   {:git/url "https://github.com/clojure/clojurescript.git"
                    :tag "r1.10.773"
                    :sha "790bcbf5f45d3775c15d597eee240fb3f3636681"}}}
```

This is excellent, thank you very much for the help.
