### ISSUE TITLE
No support for clojure ratio type

### ISSUE THREAD

**Issue by pangloss** [djblue/portal#28]
Instead of showing a ratio like `1/3` it just shows `#ratio[2]`

**Comment by djblue** [comment]
Hi @pangloss, thanks for reporting the issue. This should be a pretty easy fix, just need to account for this type of tagged value [here](https://github.com/djblue/portal/blob/master/src/portal/ui/inspector.cljs#L39) and implement a ratio renderer. Do you have any interest in submitting a PR?

**Comment by pangloss** [comment]
Hi, sorry I'm busy with a couple of other projects so don't think I'll have time to do the PR. Was just trying out the project, and it looks very nice and useful.

By the way I took a quick look at the code you linked and was surprised you didn't use a multimethod for that part since it seems like a good way to make the system more user-extensible. Anyway, thanks for putting together a useful tool!

**Comment by djblue** [comment]
No worries, https://github.com/djblue/portal/commit/0b44c76ddf5436fb89cd5ea5eb41ed25aee18f2b should fix it.
