### ISSUE TITLE
Provide context aware navigation.

### ISSUE THREAD

**Issue by gaberger** [djblue/portal#33]
This would be a feature enhancement currently focused on :portal.view/table such that when clicking on the index column, instead of navigating to the element which is somewhat pointless, will instead transition the view to column mode for that specific index.

**Comment by djblue** [comment]
Is the below video what you are trying to accomplish? Selecting a subset of all columns to focus on?

https://user-images.githubusercontent.com/1986211/103423983-1de20b00-4b67-11eb-80a8-3985e8591dc4.mov

**Comment by djblue** [comment]
Closing for now, feel free to re-open the issue with more info.
