### ISSUE TITLE
Provide api access to `remove-tap`

### ISSUE THREAD

**Issue by coyotesqrl** [djblue/portal#38]
While it's trivial to remove the tap (or clear all open taps), it would be nice if the api provided a mechanism to do that. I'd think either a new fn, such as
```clojure
(defn untap
  "Remove portal as a tap> target."
  []
  (remove-tap #'rt/update-value)
  nil)
```

or a side-effect of closing inspector windows like this
```clojure
(defn close
  "Close all current inspector windows and remove taps."
  []
  (remove-tap #'rt/update-value)
  (l/close)
  nil)
```

would work best.

**Comment by djblue** [comment]
Hi @coyotesqrl, thanks for pointing out the issue. I think both are valid options. Which one would you prefer?

I think another option would be to deprecate the `p/tap` function and expose a single function `p/submit` which can be used directly with `add-tap` and `remove-tap`. Would that be better?

**Comment by coyotesqrl** [comment]
I'm not clear where you're going with the `p/submit` function, but another option that occurs to me is deprecated `p/tap` and adding its functionality as a side-effect to `p/open`, with the `remove-tap` then occurring as a side-effect in `p/close`.

I've not been able to think of a use case for an open inspector without a tap in place; in fact, I sometimes forget to call `p/tap` after initially opening my inspector.

I'll put up a PR for this approach shortly.
