### ISSUE TITLE
using portal as a lib

### ISSUE THREAD

**Issue by veix** [djblue/portal#4]
is it possible to use portal as a lib and have it not spy on the whole repl?

**Comment by djblue** [comment]
Hi @veix, I'm not sure I understand your question. Currently, the main way to send values to portal is via `tap>` which should be independent of repl interactions. If your repl automatically uses `tap>` on all output values, then they will also be delivered to portal. Are you asking for another mechanism for sending values to portal?

**Comment by djblue** [comment]
Closing this for now, feel free to open it back up.
