### ISSUE TITLE
PWA - searching for Preferences folder not working when using multiple chrome profiles

### ISSUE THREAD

**Issue by brdloush** [djblue/portal#40]
According to...

https://github.com/djblue/portal/blob/master/src/portal/runtime/jvm/launcher.clj#L44-L46

...portal is looking for `~/.config/google-chrome/Default/Preference` file. But if you're using multiple profiles in your chrome, then it's likely that `Default` folder does not exist. Instead, you have `~/.config/google-chrome/Profile\ 1/Preferences`, `~/.config/google-chrome/Profile\ 2/Preferences` etc.

It might be better to either
- look recurively for all `Preferences` files under `~/.config/google-chrome/`
- allow user to somehow override the folder location manually via some options map, system ENV property would be enough IMO

By the way it might be a good idea to write some PWA information in README.md and mention that: 
- you can visit djblue.github.io/portal and click "Install portal...` 
- thanks to that, portal will preferrably try to run the PWA instead of generic chrome window
(I hope I got this right :smile: )

**Comment by djblue** [comment]
Hi @brdloush, is this something you have interest in submitting a pull request for?

**Comment by djblue** [comment]
Should be fixed in `0.9.0`, thanks again for the PR @brdloush !

**Comment by brdloush** [comment]
Thank you as well. Glad to have helped.
