### ISSUE TITLE
Incompatible with http-kit protocols?

### ISSUE THREAD

**Issue by nickbauman** [djblue/portal#48]
When I create a user.clj like this:

```
(ns user
  (:require [portal.api :as p]))

(defn portal []
  (p/open)
  (add-tap #'p/submit))
```
  
  and load it into an nREPL, I get:
  
  `Syntax error (IllegalArgumentException) compiling http/server-stop! at (portal/runtime/jvm/launcher.clj:68:3). No single method: server_stop_BANG_ of interface: org.httpkit.server.IHttpServer found for function: server-stop! of protocol: IHttpServer`

**Comment by djblue** [comment]
@nickbauman I think this might be a dependency conflict issue. Do you know what version of http-kit you have on your classpath?

**Comment by nickbauman** [comment]
I have 
`http-kit/http-kit          {:mvn/version "2.4.0"}`

**Comment by nickbauman** [comment]
So it looks like upgrading to 2.5.3 version of http-kit and upgrading to 0.10.0 of portal fixes this problem. Thanks @djblue !!!
