### ISSUE TITLE
Issues on Firefox

### ISSUE THREAD

**Issue by plexus** [djblue/portal#54]
Thanks for the great tool! I noticed some issues on Firefox, so I figured I'd open an issue to help track these.

- Command Palette doesn't show any choices

You can use the command palette, by typing in what you want and hitting enter, but the list of options shows as empty.

- Command Palette keyboard shortcut is unavailable

It's currently bound to Ctrl-Shift-p (on non-mac), which in FF opens a private browsing window. Seems it won't let you override that. As mentioned before in Slack my suggestion would be to use  (perhaps in addition) `ctrl-j`, as used in Nextjournal.

**Comment by djblue** [comment]
Hi @plexus,

Just pushed up https://github.com/djblue/portal/commit/b9cd86725efa5d260aaecd7649e44d55802e4dc8 with some fixes. The hidden issues was a small css error and I added the `ctrl-j` binding alongside `ctrl-shift-p` for opening the command palette. The changes are deployed to the [pwa](https://djblue.github.io/portal/). If you could please verify that these changes resolve your issue, I can release `0.11.1`.

**Comment by plexus** [comment]
Thanks! I had a play with it yesterday, all works as advertised!
