### ISSUE TITLE
Shortcut for search

### ISSUE THREAD

**Issue by latacora-gabriel** [djblue/portal#55]
Hi @djblue,
  Would it be possible to provide a shortcut for focusing on the search/filter input? Perhaps '/'? I could give this a shot sometime soon if you'd like. Could also be useful to mention the shortcuts available in https://github.com/djblue/portal/blob/b9cd86725efa5d260aaecd7649e44d55802e4dc8/src/portal/ui/commands.cljs#L175 from the readme.
Thanks again for the awesome tool! Been using it at work. Cheers

**Comment by djblue** [comment]
Hi @latacora-gabriel,

I would eventually like to provide users the ability to customize their shortcuts. The data-structure you linked has evolved over time and I'm still playing with it a little. When it matures, I'll expose it via config. Until then, I'm fine with adding it directly to portal.

You need an a dom reference to this [input](https://github.com/djblue/portal/blob/master/src/portal/ui/app.cljs#L192), which you can probably store in a top level atom. Then you can add a [command](https://github.com/djblue/portal/blob/master/src/portal/ui/commands.cljs#L588) that calls focus on that dom node. The final step would be adding the shortcut to invoke the command.

Thanks for the kind words!

**Comment by djblue** [comment]
Hi @latacora-gabriel, I went ahead and implemented this with https://github.com/djblue/portal/commit/dcbb0840b9a23d0e86738e1bf4bae54c8ef3cfbc. Should be part of the next release. You can try out the ux [here](http://djblue.github.io/portal).

**Comment by latacora-gabriel** [comment]
Thanks! Sorry I never got around to this. Works great!
