### ISSUE TITLE
Support vim keybindings

### ISSUE THREAD

**Issue by qleguennec** [djblue/portal#65]
The user should be able to at least use `h`, `j`, `k`, `l` for navigation, and maybe easily customize their keybindings through a config file. If this is easily doable and wanted as a feature, I can give it a try.

**Comment by djblue** [comment]
Hi @qleguennec, I've been meaning to add those key mappings to portal. Just pushed up https://github.com/djblue/portal/commit/875751d2bade48dcd5cdba34d26cc76ea459b63d. You can try the change out at [djblue.github.io/portal](https://djblue.github.io/portal/).

**Comment by djblue** [comment]
This should be resolved with the release of [0.15.0](https://github.com/djblue/portal/releases/tag/0.15.0).
