### ISSUE TITLE
Feature Request: Shortcut for selecting the element in the portal list

### ISSUE THREAD

**Issue by davidpham87** [djblue/portal#78]
Hello :-)

Thanks a lot again for the client API. I am starting to use portal in my workflow with emacs and portal is basicaly allows me to browse data from various projects.

May I just ask if it possible to focus the data panel with a shortcut?  I am using the TAB key now to cycle/navigate, but it would be helpful to have a shortcut (much like CTRL-j).

Best regards,
David

**Comment by djblue** [comment]
Hi @davidpham87, I think ctrl-j is already used as an alternative to `cmd + shift + p`, but I would be down to add a `portal.ui.commands/select-root` command and map it to another shortcut, not sure what though 🤔 

I probably won't have time to do it soon, so if you feel like giving it a shot, you can look at [`portal.ui.commands`](https://github.com/djblue/portal/blob/master/src/portal/ui/commands.cljs#L666-L676). Let me know if you have any questions.

**Comment by juan-ignacio-848** [comment]
Speaking about shortcuts, it would be nice to be able to mark/unmark elements with `SPC` as an alternative to CMD/ALT + click

**Comment by djblue** [comment]
@davidpham87, I think now with https://github.com/djblue/portal/commit/83365c80f92d8f480cb2664238939c9554d98ac6, anytime you try relative selection and nothing is selected, the root is selected. I think this should solve your issue and will be part of the next release. If you consider this a solution, feel free to close the issue.

@juan-ignacio-848, I'll see about adding keyboard only multi-select UX.
