### ISSUE TITLE
Feature Request: user defined callbacks on vega views

### ISSUE THREAD

**Issue by Cyrik** [djblue/portal#79]
I'd love to be able to extend already defined views. I've been thinking that the easiest way to get most of the functionality would be by being able to pass in an optional map of functions that can be called back into the hosting runtime.

For me its mostly interesting on the Vega view, so playing around with it I came up with the following modification:

```clojure
(defn vega-embed [opts value]
  (let [theme (theme/use-theme)
        doc (deep-merge (default-config theme) value {:title ""})
        portal-opts (:portal-opts value)
...
...
    (react/useEffect
     (fn []
       (when-let [view (.-current view)]
         (let [width (- width 2
                        (* 2 (:padding theme)))
               callback (fn [event item] 
                          (when-let [callback (:click-callback portal-opts)]
                            (when-let [datum (if (.hasOwnProperty item "datum") (.-datum item) nil)]
                              (state/invoke callback (js->clj datum)))))]
           (.width view width)
           (.height view (* width 0.8))
           (.addEventListener view "click" callback)
           (.run view))))
     #js [init (.-current view) width])

```

This would have to be cleaned up and extended, but it works if you register any :click-callback passed in function as a command.

Would you be interested in a pull request for a clean version of the feature?

Oh btw, my usecase would be in [omni-trace](https://github.com/Cyrik/omni-trace) to be able to callback into the code so that the flamegraph can be extended or functions can be rerun.

I'd have just defined my own view, but unless I'm mistaken its not currently possible to do so without forking the ui code.

**Comment by djblue** [comment]
Hi @Cyrik!

You are correct, viewers are not currently extensible due to how the Portal UI is built and packaged in the jar.

I think the notion of runtime extensibility is interesting. I think we might want to iterate on the API a bit though. Also, if I remember correctly, I think vega has their own notion of event's we might want to plug into.

I am experimenting with pulling in sci to allow user extensibility in the ui runtime. However, this would provide a pretty minimal development environment, no repl or hot reloading. Ideally, you would be able to use your preferred cljs development tools and consume portal from source, but there are also issues with that (node_modules).

**Comment by Cyrik** [comment]
> I think the notion of runtime extensibility is interesting. I think we might want to iterate on the API a bit though. 

Do you have any ideas/suggestions on the api? At least for my use-case it would be pretty nice to just be invoked back into a registered command, although it would help if the command result would do something useful back in vega.

> Also, if I remember correctly, I think vega has their own notion of events we might want to plug into.

It actually has multiple: the one i used [addEventListner](https://vega.github.io/vega/docs/api/view/#view_addEventListener) and a little harder to use but more general: [signal listener](https://vega.github.io/vega/docs/api/view/#view_addSignalListener) . Having the addEventListner available for easy cases and the other one as a two way binding into signals might be a good way to go.

> I am experimenting with pulling in sci to allow user extensibility in the ui runtime. However, this would provide a pretty minimal development environment, no repl or hot reloading. Ideally, you would be able to use your preferred cljs development tools and consume portal from source, but there are also issues with that (node_modules).

Yeah consuming from source seems problematic, especially if you want to provide a custom view as an added library. I haven't played around enough with cljs bundling yet. Maybe it would be possible to offer some sort of hook point for new views, where the new view is just consumed as a .js file or possibly even a string that gets eval'd as js? Then it would be possible to pass new views into a running portal ui and developing them could be done in cljs and compiled to an esm module with shadow.

**Comment by Cyrik** [comment]
I've played around more with vega callbacks and at this point, I think we can get 90% of the possibilities by just allowing commands to be bound to signals. That way all the actual code would be inside the vega spec and on the Clojure server side and if it's just "light" interaction you wouldn't need your own custom view.

```clojure
    (react/useEffect
     (fn []
       (when-let [el (.-current absolute)]
         (-> (vegaEmbed el (clj->js (assoc doc :width width)) (clj->js opts))
             (.then (fn [value]
                      (set! (.-current view) (.-view value))
                      (doseq [{:keys [:signal :command]} portal-opts]
                        (. (.-view value) addSignalListener signal #(state/invoke command (js->clj [%1 %2]))))
                      (set-init! true)))
             (.catch (fn [err] (js/console.error err)))))
       #(when-let [view (.-current view)]
          (.finalize view)
          (set! (.-current view) nil)))
     #js [])
```

I'd love it if you would put this change into the main vega view.

Updating the data without resending the whole thing still needs some work on the API. But that can come later.

**Comment by djblue** [comment]
@Cyrik, I think since we went the cljs extensibility route, this issue can be considered resolved. Feel free to open it back up if not.
