### ISSUE TITLE
Multi-select doesn't work on Ubuntu (on the portal-talk repo)

### ISSUE THREAD

**Issue by mchughs** [djblue/portal#83]
Tried using `alt` and a bunch of other key combos and nothing worked to be able to multi-select. :(

Using a basic Dell Keyboard.

I actually cloned this repo onto my machine and tried with the dev build, and there, multi-select **did** work.
However on the portal-talk repo it doesn't. Really unclear why. I added a keyboard event listener onto the chrome window running portal and it properly captures the `alt` key being pressed.

**Comment by mchughs** [comment]
:facepalm: I see you just added `alt` for multi-select 14 days ago and the last release `0.18.0` was 15 days ago. My bad. Looking forward to `0.19.0` :smile:

**Comment by djblue** [comment]
@mchughs, sorry about that. Should have waited to document it until it was released.
