### ISSUE TITLE
Multiple selection not working in Manjaro

### ISSUE THREAD

**Issue by juan-ignacio-848** [djblue/portal#86]
I'm trying to select multiple values by holding `ALT` and clicking on them, the result is that it just selects the last one I clicked.

This is my system information:

```shell
$ uname -a
=> Linux nmkip 5.10.79-1-MANJARO #1 SMP PREEMPT Fri Nov 12 20:26:09 UTC 2021 x86_64 GNU/Linux
```

This is what is being returned by `window.navigator.platform` 

```javascript
window.navigator.platform
=> 'Linux x86_64'
```

**Comment by djblue** [comment]
I think this problem might be related to https://github.com/djblue/portal/issues/83, will be fixed in the next release since it isn't release yet. Sorry for any confusion.

**Comment by juan-ignacio-848** [comment]
Great, thanks!
