### ISSUE TITLE
Vega-lite viewer cuts off right hand edge of chart

### ISSUE THREAD

**Issue by hugoduncan** [djblue/portal#99]
When viewing a vega-lite chart, it looks like the vega-lite view extends past the right hand edge of the visible component.  The red highlighting around the selected portal item is missing on the right hand edge of the vega-lite view.  This leads to some data points not getting displayed.

This is with 0.19.2 running from clojure on a mac.

**Comment by djblue** [comment]
Hi @hugoduncan, do you have some sample data to reproduce? Thanks for the bug report.

**Comment by hugoduncan** [comment]
Apologies for the omission.
```clojure
{:$schema "https://vega.github.io/schema/vega-lite/v5.json"
             :data []
             :vconcat [{:data {:values [{:x 0 :y 1} {:x 1 :y 2} {:x 3 :y 1}]}
                        :encoding
                        {:x {:field "x" :type "quantitative"   }
                         :y {:field "y" :type "quantitative"}}
                        :mark "point"}]}
```

**Comment by djblue** [comment]
@hugoduncan, sorry it took so long but this should be fixed in the next release.
